### ISSUE TITLE
Preview mode for markdown notes in Preview

### ISSUE THREAD

**Issue by imed-ghomari** [mProjectsCode/obsidian-lemons-search-plugin#1]
**Is your feature request related to a problem? Please describe.**
Hi, thank you for the plugin. The problem is that whenever I search for a markdown file, I see the "source mode" version of the file in the preview section, which doesn't make it easy to identify the file if it has a lot of code blocks or callouts.

**Describe the solution you'd like**
Make the markdown file appear in the "preview mode" in the preview section.

**Comment by mProjectsCode** [comment]
This has been done intentionally in the name of performance. I will consider adding a setting to switch the preview mode to render the markdown.

**Comment by hyperphysin** [comment]
I want this feature too.

**Comment by mProjectsCode** [comment]
I changed the default behavior to render markdown.
