### ISSUE TITLE
Failed to Install Plugin

### ISSUE THREAD

**Issue by ThisTheThe** [mProjectsCode/obsidian-lemons-search-plugin#3]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**

Installation fails when attempting to install the plugin from the built-in plugin browser.

Screenshots for further clarity:
![24-10-19_23-45-07-515](https://github.com/user-attachments/assets/a90bb0bf-e027-4a7a-9639-5d8aeaf37cb6)
![Obsidian_24-10-19_11PM-45-34_460](https://github.com/user-attachments/assets/6446b32b-87fe-4374-b66f-c61b83b0a317)

**To Reproduce**

-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.0.1

**Comment by mProjectsCode** [comment]
I can't reproduce this. Your Obsidian probably can't reach the GitHub servers.
