### ISSUE TITLE
Highlight the keywords in search result

### ISSUE THREAD

**Issue by Moyf** [mProjectsCode/obsidian-lemons-search-plugin#6]
**Is your feature request related to a problem? Please describe.**
No, not related to a problem.

**Describe the solution you'd like**
![image](https://github.com/user-attachments/assets/30d9a453-044d-450b-8583-4b0b1a1bd437)
I hope that the keywords could be highlighted like this image, so that we can recognize the words easily and quickly.

> BTW, the extension ".AppxBundle" is also searched, which looks kinda strange? Adding an option (or search commands) for specifying `including extension` might be useful in some cases.

**Additional context**
![image](https://github.com/user-attachments/assets/76a4f161-a1d5-4ae7-b77d-b6eafd306210)
I know sometimes the fuzzy search would search "A"+"P"eo"ple", maybe use different styles for "Complete match" and "Partial match"?

**Comment by mProjectsCode** [comment]
There is no highlighting in the file preview because the plugin does not search the file content. The current highlighting colors mimic base Obsidian and are dependent on your theme. If you want to change them, you can do so via a CSS snippet.

**Comment by Moyf** [comment]
I see, understood, thanks!
